My UserScripts
** UserScript? What's A UserScript?
If you don't know what userscripts are, you can read about [[http://bit.ly/ypj8z2][Greasemonkey]]. I happen to prefer the [[http://bit.ly/xYcpv7][Scriptish]] add-on over Greasemonkey but the GM wiki page seems to be the best description I have found about userscripts. (If you have a better reference, I'd love a pointer.)

*** My UserScripts Online
Many of my userscripts can be found on my UserScripts.org [[http://userscripts.org/users/66250/scripts][profile page]].

** Timely Google Search
By default, a Google search returns all results dating to the beginning of time (at least internet time). I find that for over 99% of my searches[1] I either only care about information from the past year or that there are enough new or updated postings in the past year that I don't need to search further back. 

As a quick example, as of the time of writing this (13 April 2012), a Google search for /Google map help/ returns 836 million hits for the [[http://bit.ly/J9lf6J][past year]] compared to 1.2 billion hits for [[https://www.google.com/search?q=google%20search%20help&ie=utf-8&oe=utf-8][all time]]. 

While the nearly one third reduction in total search hits likely doesn't matter much to me as I probably will never look at most of them, limiting the search to the past year eliminates links to old articles such as [[http://bit.ly/HS4Z9Q][this one]]. That 2006 blog article is the 11^th hit on my /all time/ search, [[http://en.wiktionary.org/wiki/YMMV][YMMV]][2]. Personally, I am infuriated when I find that I have wasted my time reading some long-outdated article. 

The [[https://raw.github.com/Neil-Smithline/UserScripts/master/timely-google-search-year.user.js][Timely Google Search Year]] userscript defaults all Google searches the past year. If you want to search all of eternity, you can simply hit the /Any time/ link on the left side of the Google results and you'll have your unrestricted search. 

** AMO: Up Top Version Info
[[http://bit.ly/HJCDRj][AMO]] is the site that provides discovery, download, and installation of add-ons for [[http://bit.ly/IGtTL8][Firefox]] and other [[http://bit.ly/HJCSM7][Mozilla]] [[http://bit.ly/HJD0Lt][applications]]. When searching on AMO, it cleverly restricts add-ons to those that match the version of Firefox that you are using. 

But since Mozilla changed their [[http://bit.ly/IGtqso][release schedule]] to release a new version every 6-weeks, add-ons have had a hard time staying current. So every 6-weeks, every add-on becomes outdated and must go through Mozilla's AMO update process to be considered safe to work with the newest version of Firefox. Mozilla's cautious approach to declaring add-ons compatible with new releases helps to ensure that Firefox is a stable application.

But some users (eg: me!) are willing to run an add-on that was considered compatible with a previous version of Firefox but not the version the user is currently running. But this must be done with care. The risk of installing an incompatible add-on grows with each release. 

For example, if you are running Firefox version 13, you may be comfortable installing any add-on that was compatible with Firefox version 12 and willing to risk installing your favorite add-ons that were compatible with Firefox version 11 or even 10. 

Also, as a general rule, you never, and I mean /never ever/, want to install an add-on that isn't compatible with a Firefox version of 4 or more. 

Unfortunately, the default AMO layout has the version information at the bottom of an add-on's page and hidden until you click on the /Version Information/ box. 

The /AMO: Up Top Version Info/ userscript copies the most relevant parts of the version information and puts it right on the top of the page next to the /Install/ button. 

The script tries to style the /up top/ version information to flow naturally with the existing page. It puts the version information in a box that can be themed for different colors (for now you must edit the script to change themes - sorry). 

The box is also dynamically sized so that it can handle /Install/ buttons of different width. For example, at the time of writing this (13 April 2012), the [[http://bit.ly/HHEBCi][My Homepage]] add-on has a wider /Continue to Download/ button instead of an /Install/ button. The dynamic sizing also allows for buttons of different widths that will occur in non-English pages.

# LocalWords:  Userscripts

** Footnotes

[1] Yes. I've checked Google's history of my searches to know that 99% is an accurate number.

[2] Google has optimized their search engine for speed over accurate results. This optimization can lead to getting slightly different results on the same search.
